language: python
python:
  - "3.5"

sudo: required
dist: trusty

install:
  - pip install -r requirements.txt
  - pip install coverage

before_script:
  - python cvdb/generate_passwords.py cvdb/passwords.py
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source='./viewcv' manage.py test -v2 viewcv
  - coverage report

after_success:
  - codecov
