language: python
python:
  - "3.5"

sudo: required
dist: trusty

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

before_script:
  - python cvdb/generate_passwords.py cvdb/passwords.py
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source=api01,users,viewcv manage.py test -v2
  - coverage report

# after_success:
#   - codecov
