version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install apt packages
          command: |
            sudo apt-get update
            sudo apt-get install libpangocairo-1.0-0
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Python packages
          command: |
            pip install -r requirements.txt
            pip install coverage
            pip install codecov
      - run:
          name: Generate site config
          command: python cvdb/generate_site_config.py cvdb/site_config.py
      - run:
          name: Update database tables
          command: |
            python manage.py makemigrations
            python manage.py migrate
            python manage.py makemigrations viewcv
            python manage.py migrate viewcv
      - run:
          name: Run unit tests
          command: python manage.py test
      - run:
          name: Run coverage
          command: |
            coverage run --source=api01,users,viewcv manage.py test -v2
            codecov
            coverage report
workflows:
  main:
    jobs:
      - build
