---
- name: Prepare server
  hosts: all
  become: true
  tasks:
    - name: Check connection
      ping:

    - name: Install required packages
      yum: pkg={{item}} state=present
      with_items:
        - nginx
        - git
        - python-virtualenv

    - name: Start Nginx
      service: name=nginx state=started

    - 